### ISSUE TITLE
reaction.users.remove is not a function

### ISSUE THREAD

**Issue by iMagic142** [NicksWorld/replypages-discordjs#1]
When I react to the message that the bot sent, this error apprears: TypeError: reaction.users.remove is not a function

**Comment by NicksWorld** [comment]
Can you tell me what version of discord.js your bot is running?

**Comment by iMagic142** [comment]
latest.

**Comment by NicksWorld** [comment]
Have you tried updating the module?

**Comment by NicksWorld** [comment]
If you have updated, try going back a version. A commit might have had a bug in it. Right now I am at school and cannot edit or check the code I last published. When I get home I will make sure to see what may be causing that.

**Comment by iMagic142** [comment]
Problem solved!

On Mar 20, 2018 1:25 PM, "Nicholas McDaniel" <notifications@github.com>
wrote:

If you have updated, try going back a version. A commit might have had a
bug in it. Right now I am at school and cannot edit or check the code I
last published. When I get home I will make sure to see what may be causing
that.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/NicksWorld/replypages-discordjs/issues/1#issuecomment-374563349>,
or mute the thread
